name: network_monitor_cp
description: "Connectivity_plus wrapper to monitor network status in rela time"
version: 0.0.3
homepage: https://github.com/avinashk369/network_monitor
repository: https://github.com/avinashk369/network_monitor
issue_tracker: https://github.com/avinashk369/network_monitor/issues

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0




flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg

